name: Others - PR Events Workflow

on:
  pull_request_target:
    types: [opened, reopened, synchronize]

jobs:
  check_pull_requests:
    runs-on: ubuntu-latest
    steps:
      - name: Run logic for other events
        run: echo "Handling opened, reopened, and synchronize events"
